import { Inter, Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"], weight: ["800"] });

export const metadata = {
  title: "Advice Generator Application",
  description: "Generated by create next app",
  image: "./favicon-32x32.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>{children}</body>
    </html>
  );
}
